# fly.toml file generated for winter-frog-3008 on 2022-12-09T10:05:38+08:00

app = "winter-frog-3008"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  ASR_MODEL = "tiny"

[experimental]
  allowed_public_ports = []
  auto_rollback = true
  private_network = true

[[services]]
  http_checks = []
  internal_port = 9000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "1m"
    restart_limit = 0
    timeout = "2s"
