# fly.toml file generated for winter-frog-3008 on 2022-12-09T10:05:38+08:00

app = "winter-frog-3008"
kill_signal = "SIGINT"
kill_timeout = 5

[env]
  ASR_MODEL = "tiny"

[checks]
  [checks.up]
    grace_period = "30s"
    interval = "1m"
    method = "get"
    path = "/docs"
    port = 8080
    timeout = "10s"
    type = "http"
